name: Scan with Xray and promote

on:
  push: 
    branches: 
    - main
  pull_request: 

jobs: 
  Build:
    name: Publish and Scan with Xray
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
    
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: ${{ secrets.JF_URL }}
          # JFrog Platform auth creds
          JF_PASSWORD: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_USER: ${{ secrets.JF_USER }}
      
      - name: Publish to Staging repo
        env: 
          # JFrog Platform auth creds
          ARTIFACTORY_USER: ${{ secrets.JF_USER }}
          ARTIFACTORY_KEY: ${{ secrets.JF_ACCESS_TOKEN}}
        run: |
          ./gradlew jib
          jf rt bp --server-id=github --build-name=${{ github.repository }} --build-number=${{ github.run_number }} --fail=true
          jf bs ${{ github.repository }} ${{ github.run_number }}
          
      - name: Promote to Artifactory
        env: 
          # JFrog Platform auth creds
          ARTIFACTORY_USER: ${{ secrets.JF_USER }}
          ARTIFACTORY_KEY: ${{ secrets.JF_ACCESS_TOKEN}}
        run: echo 'lol'
      
      
      
          