name: Scan with Xray and Publish to Artifactory

on:
  push: 
    branches: 
    - main
  pull_request: 

jobs: 
  Build:
    name: Publish and Scan with Xray
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
    
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: ${{ secrets.JF_URL }}
          # JFrog Platform auth creds
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_ACCESS_TOKEN }}

      
      - name: Publish to Staging repo
        env: 
          # JFrog Platform auth creds
          ARTIFACTORY_USER: ${{ secrets.JF_USER }}
          ARTIFACTORY_KEY: ${{ secrets.JF_ACCESS_TOKEN}}
        run: |
          ./gradlew jibDockerBuild --image=test:latest
          jf docker scan test:latest --fixable --watches 'Security_watch_1'
    
      
      
      
          