name: Publish and Scan with Xray

on:
  push: 
    branches: 
    - main
  pull_request: 

jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Xray scan
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          # JFrog platform url (for example: https://acme.jfrog.io) 
          JF_URL: ${{ secrets.JF_URL }}
          # JFrog Platform access token
      - run: |
          ./gradlew jibBuildTar
          jf scan build/jib-image.tar --fixable --watches 'Security_watch_1'
          ./gradlew jib
          